### ISSUE TITLE
Set device to system default in constructor.

### ISSUE THREAD

**Issue by MichealReed** [alexmercerind/flutter_audio_desktop#11]
Miniaudio has https://github.com/mackron/miniaudio/issues/126, which we can use to automatically set the playback device to the system default. Will implement this as soon as https://github.com/alexmercerind/flutter_audio_desktop/pull/10 lands.

**Comment by alexmercerind** [comment]
Really Awesome! This actually was really annoying for the people who had more than one audio cards & there really wasn't a way to get the preferred one till now.

**Comment by alexmercerind** [comment]
I don't know if you know it yet or not, but I made this library for my personal usage as there wasn't any library to play audio on Flutter Windows & Linux (this is the only one still).
I don't have any CS degree, I just like to code & make stuff. And I didn't really work on this since then, as we know C++ isn't easy compared to other languages out there (neither I have too deep knowledge... It's what I learnt in school).

When I started making this, there wasn't any official guide from Flutter to make plugins for Windows or Linux (I don't think we have even now). I just made this by reading their engine code, that slight example & trial-error.

Nice to meet you 😊!

**Comment by MichealReed** [comment]
Definitely don't stop coding, you have done a great job here, even more-so with the above considered. I think this package can become a very popular package within the flutter community, especially if we continue to add tests, expand platform compatibility and add features like recording. Really appreciate you building this, I was looking for a way to synthesize audio on desktop and this, along with miniaudio was the perfect launchpad for that.

If you have discord, I discovered today that miniaudio has a server: https://discord.gg/9vpqbjU

We can discuss/plan more via Discord for all interested in collaboration. Just DM me, Micheal#5434 after you join the server.
