### ISSUE TITLE
Pointer to temporary object

### ISSUE THREAD

**Issue by Gregor14** [alexmercerind/flutter_audio_desktop#17]
Hello,
I just start to familiarise with your code (due my own problems with miniaudio I try to see, how other people done this). Probably I found error in audioplayer.hpp.

https://github.com/alexmercerind/flutter_audio_desktop/blob/8f5f066acb47783074cc5c7ab569c7d898fd89f3/audioplayer/audioplayer.hpp#L123-L126

ma_device_id is an union. In function initDevice and in initDeviceWave is passed such union as parameter, so this is temporary object. So, stored in variable pDeviceID pointer to this parameter (selectedDeviceId) will be invalid, when we leave function.

**Comment by MichealReed** [comment]
Thanks for looking over the code, please feel free to make comments regarding code aesthetics or conventions as well. Ah yes, that does look a little odd, thanks for finding that. It should not cause any issues though, deviceConfig doesn't even necessarily need to be persistent either. After init is ran any changes to device config requires re-initialization. Feel free to submit a PR with a better approach, otherwise I will rework in upcoming updates.
