### ISSUE TITLE
When play() is executes it shows audio channels instead of playing audio

### ISSUE THREAD

**Issue by humble-git** [alexmercerind/flutter_audio_desktop#3]
Hello, 
I'm trying to use your plugin in my Windows app, but when i run the play() the terminal displays my audio channels instead of playing actual sounds as follows. Is there any way to choose channel while playing? 

```
0 - LG IPS FULLHD (2- NVIDIA High Definition Audio)
1 - Headset (MDR-ZX330BT Hands-Free AG Audio)
2 - Headphones (MDR-ZX330BT Stereo)
3 - Speakers (Realtek(R) Audio)
```

**Comment by alexmercerind** [comment]
My machine only has one audio device... So I never experienced this. I think I should add a device selection.
It picks the first device by default (which is probably not right in your setup).

**Comment by humble-git** [comment]
Appreciate your help.

**Comment by alexmercerind** [comment]
👋 Hello @humble-git !

I added a simple method to change the audio playback device. You can confirm the fix by running plugin from the [vnext](https://github.com/alexmercerind/flutter_audio_desktop/tree/vnext) branch. 

**Let me know if audio plays for you now.** You can pass ```debug:true``` while initiating the AudioPlayer class for additional logs.

You gave me YOUR SETUP as follows:
```
0 - LG IPS FULLHD (2- NVIDIA High Definition Audio)
1 - Headset (MDR-ZX330BT Hands-Free AG Audio)
2 - Headphones (MDR-ZX330BT Stereo)
3 - Speakers (Realtek(R) Audio)
```

I think that device 3 in the list should be your preferred playback device (instead of 0). 
To select device 3 for playing audio, just call the following method:
```dart 
audioPlayer.setDevice(deviceIndex: 3);
``` 
**NOTE:** This must be called before the ```load``` method of the ```AudioPlayer``` class.

🔧 If it still does not work for you, please provide me the full log in your console. Make sure that you're loading MP3, WAV or FLAC. (If the file is corrupt or unsupported, then you'll see sample rate & channel count as 0 in terminal)


**My Command Prompt gives following log... (I passed debug: true for extra logs, when initiating the AudioPlayer class)**
```bash
0 - Speakers (Realtek(R) Audio)
Syncing files to device Windows...                                 434ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:53998/M9I98bDi9zQ=/
Selected Device: 0 - Speakers (Realtek(R) Audio)
Channel Count: 2 
Sample Rate  : 48000
Loaded File: C:/Users/Alex Mercer/Music/music.mp3
Started Playback. await = false
Set Volume: 0.5
Paused Playback.
```

I'll add v0.0.7 on pub.dev once you confirm the fix.

😃 Thankyou! Hope this helps.

**Comment by alexmercerind** [comment]
Hi @humble-git,

You can test the simple example made by me directly as follows: (Don't forget to change the deviceIndex as 3 in following line)

https://github.com/alexmercerind/flutter_audio_desktop/blob/738a9e0c869f37028cdaeaac437f58884b1b24af/example/lib/main.dart#L84

```
git clone --single-branch --branch vnext https://github.com/alexmercerind/flutter_audio_desktop.git --depth=1
```
```
cd flutter_audio_desktop
```
```
flutter pub get
```
```
cd example
```
```
flutter run
```

**Comment by alexmercerind** [comment]
Closing this one. Feel free to leave feedback or reopen.
