### ISSUE TITLE
Could you collaborate with this repository?

### ISSUE THREAD

**Issue by DomingoMG** [alexmercerind/flutter_audio_desktop#6]
It would make me very happy to be able to use assets_audio_player with its implementation on Windows.

In assets_audio_player supported by Mac, you can parse the operation for implementation.

I hope I can count on you @alexmercerind for this collaboration.

https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/386
https://github.com/florent37/Flutter-AssetsAudioPlayer

**Comment by alexmercerind** [comment]
👋 Greetings @DomingoMG !

I'll be really happy to add support to assets_audio_player for Windows & Linux.
But **I can only add the features which I have added here in my project only**, because:
- I'm using miniaudio for playing audio on both Windows & Linux. There aren't many good libraries for playing audio in C++, most are game engine oriented. I cannot add network streaming. The ones which are good are not in public domain.
- Flutter on Windows & Linux uses C++ unlike swift on mac or java on android for method channels (which isn't the best enjoyable language to write neither I have deep knowledge of it).
- I'm just an alone 18 year old student.

Even when making this (flutter_audio_desktop), I just added few features which I wanted to use & made very basic implementation on top of miniaudio. Doing it in C++ isn't easy because most of libraries are low level (and work that one has to do is far from mapping functions present in Java or Swift to Dart).

Initially even in flutter_audio_desktop, I switched to three different libraries namely irrKlang, BASS & now miniaudio. 
Main reason for using miniaudio now is because, it is open source & completely in public domain, and so is flutter_audio_desktop. But still you can see it just supports MP3, WAV, FLAC & OGG.

**Comment by alexmercerind** [comment]
In other words, I'm not the most talented person to choose for collaboration. There are many other C++ experts out there. But, if you wanna see the features that I already have here, then I might help.
Even before that, I would like to have an confirmation from you if this library is even working on your PC as there isn't much testing that I have performed.
Thankyou.

**Comment by DomingoMG** [comment]
👋 @alexmercerind

Your library works fine for me.
- Windows 10 Professional 64 Bits.

I have checked an error with the path:
It works satisfactorily:
D: \ Audios \ Regueton \ Abraham Mateo - Loco Enamorado.mp3
It does not work correctly:
D: \ Audios \ Regueton \ Abraham Mateo - A Cámara Lenta.mp3 => á

I am 23 years old, I have no knowledge of C ++, only Java, Php, Dart, Javascript. I don't mind collaborating and learning C ++, to advance the work.

My idea is to try to make the same tools that assets_audio_player brings but for Windows and Linux. Since it is already implemented on Mac.

If you need help or contact me, I leave you my twitter:
https://twitter.com/DomingoMG97

Nice to talk to you and I hope to collaborate with you very soon, greetings.

**Comment by DomingoMG** [comment]
I know we do not have much knowledge but you have already achieved the minimum to make it functional, little by little we will achieve it. 💪

**Comment by beevelop** [comment]
Wow man, you are both awesome @DomingoMG & @alexmercerind. Can the whole NeoSEALs team and I be of any assistance with this challenge? Let's make this happen 🚀

**Comment by MichealReed** [comment]
It seems that this project provides a better base for support of all platforms. May be better served to add additional platform support / features here versus focusing efforts on the AssetsAudioPlayer library.

**Comment by syleishere** [comment]
That would be great so works on all desktops. I think end goal should possibly to integrate with https://pub.dev/packages/audio_service, so developers don't have to do both of these. I think the code would need to run in an isolate in background somehow.

**Comment by alexmercerind** [comment]
@syleishere.

I agree upon that [audio_service](https://pub.dev/packages/audio_service) is just unnecessary, a single plugin should do it all like [flutter_assets_player](https://github.com/florent37/Flutter-AssetsAudioPlayer).


But, "audio service" things on desktop computers are different than on mobile. The way things are handled on a mobile operating system are different than on a mobile.

Two of the things, that I aim for are:

![1](https://user-images.githubusercontent.com/28951144/110230526-96829080-7f37-11eb-96e1-ad7d8ca42cf5.PNG)
![alex](https://user-images.githubusercontent.com/28951144/110230528-98e4ea80-7f37-11eb-9b98-6635c022b815.PNG)

**Comment by alexmercerind** [comment]
@syleishere 
BTW, since Flutter for UWP is also on the way, which means I will be able to use modern Windows APIs from C++/winRT headers, since the library i.e. miniaudio I'm using right now doesn't have much that I can do.

So, just settling on one kind of approach will be just not good.

Flutter for Windows & Linux is still in alpha, so there is no way this plugin is going to be stable or production oriented presently. 

What main achievement of this plugin is to it working somehow, when there are literally no other plugins made for Windows or Linux yet to look at.

**Comment by alexmercerind** [comment]
BTW since, both flutter_audio_assets and audio_service actually ask you to add metadata yourself (and do not read from file).

I'll add native stuff to extract media information from the file itself using [flutter_media_metadata](https://github.com/alexmercerind/flutter_media_metadata). I'll bring it to Windows easily.

This will be cool to have.

**Comment by alexmercerind** [comment]
Ultimate goal of the project will be (for now, if C++/winRT headers didn't end up well for me) to use [libVLC](https://www.videolan.org/vlc/libvlc.html).

And, we all know that nothing can be a better choice than VLC for any kind of media playback / format support. Since, libVLC is cross platform, I don't have to make a separate implementation for Linux (like I have to if I use C++/winRT APIs).

Since, current plugin is really very very handy, a small package size compared to other plugins, & plays audio as it promises. So, I'll let this plugin use miniaudio, so that people can use this for their basic audio playback requirements. And, I'm thinking to work on a separate project with libVLC as base, since it is dynamically linked on Windows & developers have to keep DLLs & plugins with their executable.

**Comment by DomingoMG** [comment]
From my point of view, I think libVLC is a plugin that could fit in very well, as you mentioned, VLC works cross-platform.

It is good to try other tools to be able to evaluate which one is the best for the project.

One of the complications that could exist is that I do not know if it will be possible to perform a scan of the folders and music files on the desktop, to allow selecting the songs.

To this day, to get the metadata of the songs, I use an Apache server with PHP with the getID3 plugin, storing the information in a database.

I would be very excited if an audio plugin had all of these features:

 - Play online radio
 - Play audios online


Audio
- play
- pause
- search position
- SeekBy's position
- Forward speed
- Rewind speed
- stop
- metadata object
  - qualification
  - artist
  - year
  - bpm
  - thumbnails
  - Bit rate
  - album
  - durationInSecond
  - genreId
  - genreName
 

Play list
- next song
- back song
- getCurrentAudioPlaying
- playlistPlayAtIndex
- insertAudioToPlaylist
- removeAudioToPlaylist
- finishCurrentAudio
- loopMode (possible enum values: loopMode.none, loopMode.single, loopMode.playlist)
- playlistAudioFinish (Rx - Reactive)
- playlistFinish (Rx - Reactive)
- getPlaylist => List <audio> playlist ...
- getCurrentIndexPositionAudio
- onError (check that the audio does not load)

Audio devices
I have not managed to change the sound card via a drop down menu. @alexmercerind I would like you to see my code on the sound card change.

I don't know if I have anything left but I think it would be a complete and fundamental complement.

**Comment by syleishere** [comment]
From what I have seen is netflix uses exoplayer not VLC for android, so maybe that is something to look at. VLC would be nice for windows for sure.  Samba support would be nice. From real life parties, I have found all people want is the app to be able to play the video for a song on the google TV chromecast when they say the song outloud over remote or normal google device. Is there a way to get access to the microphone?

**Comment by alexmercerind** [comment]
I've made request for collaboration (on the issue you mentioned). The things are under progress now. 🎉

Looking forward to make Flutter more homely for Windows & Linux.

[dart_vlc](https://github.com/alexmercerind/dart_vlc) is the new project having things like playlists, network streaming & many other things in it. It is sequel to this project, though I'll possibly still maintain this plugin.
