### ISSUE TITLE
Support Multiple Players

### ISSUE THREAD

**Issue by MichealReed** [alexmercerind/flutter_audio_desktop#8]
I have a PR ready to go to add support for multiple audio players, it based off of my other PR for wave generation though so I will need to wait for that to land. I added an id parameter to all of the C++ functions, but in dart it is only required when instantiating the object. To do this, I changed argument handling so we can easily send maps from dart to C++;

I.E
```
    audioPlayer = new AudioPlayer(id: 0, debug: true);
    audioPlayer2 = new AudioPlayer(id: 1, debug: true);
```

You can preview the changes here: https://github.com/MichealReed/flutter_audio_desktop/tree/multiple_streams

Feel free to add feedback if something should change before this lands. I can only test on Windows at the moment, but Linux should work the same.

**Comment by alexmercerind** [comment]
Thankyou. I didn't work for that. Feel free to contribute and mention yourself in the project's README.
Can I add you as an collaborator on the repository?

One more thing, I wanna say is that, if there is some other more-capable library (other than miniaudio), then please let me know. I settled for using miniaudio because it was in public domain, though we know its not most feature rich.
Apart from that, I'm really not getting time to write code due to busy schedule sorry.

**Comment by MichealReed** [comment]
After spending a decent amount of time searching, I think miniaudio is a great library for cross-platform audio. Not only can we build for mobile using it, but we can also build with WASM for web. With a bit more effort, I think this packing has a chance of becoming the most popular used for audio. Another package could even include the experimental engine makron is working on for a more rich feature set.

Sure, will add myself to the readme on the next PR. Thanks!

**Comment by MichealReed** [comment]
Merged here: https://github.com/alexmercerind/flutter_audio_desktop/pull/10
