### ISSUE TITLE
Include miniaudio.h

### ISSUE THREAD

**Issue by MichealReed** [alexmercerind/flutter_audio_desktop#9]
Given the license of miniaudio, it would make sense to include the file here directly. Currently, users are required to find the file and copy it to their temporary pubspec folder before they can use this package. Bots could probably automate updates to the file here from the main repository, but manual may be better for now.

**Comment by alexmercerind** [comment]
Hi @MichealReed,

Nice to meet you. I'm not checking miniaudio.h into the source, because it is a very large file & I don't want to include someone else's work into my repository, since this is just for development. The plugin on the [pub.dev](https://pub.dev/flutter_audio_desktop) already contains miniaudio for the users.

Thankyou.

**Comment by MichealReed** [comment]
Odd, I had to manually add it to the folder pub get created, it was not automatically present for me.

**Comment by narumi147** [comment]
One suggestion, you can use `git submodule` to add [mackron/miniaudio](https://github.com/mackron/miniaudio) as submodule. Just like a link, you just need to pull the updates several weeks or months.

The flutter_qjs project also uses this way to add its c++ library as a submodule.

**Comment by alexmercerind** [comment]
@narumishi, thanks for the tip!

Though I'm working on a better implementation of this project. Now I'm fetching dependencies using CMake.

This repository will be marked as archived soon, I believe.

**Comment by narumi147** [comment]
@alexmercerind Just do it in your way, since I'm not familiar with C/C++ programming. 

Archived means the repo will be merged//migrated to another project? `audioplayers` you mentioned before? (I'm longing for null-safety migration of these two audio packages.)

**Comment by alexmercerind** [comment]
@narumishi Since, this plugin as you can tell isn't very greatly written (as it was literally first plugin ever made for Windows after Flutter team itself).

Now, I have made a new repository `flutter_vlc`, in which I'm using super powerful libVLC to bring things like network streaming, playlists, better codec/format support & better control over the playback & event handling to Flutter on Windows (and Linux later).

It's private currently. I'm nearly done on Windows part. I'll let you know once that project goes live.

I also have plans for adding support for video playback but I'm not really sure if I'll be able to pull it off as of now.

**Comment by narumi147** [comment]
Excellent work! libVLC should have more potentials on cross-platform, waiting for your publish.
